// AI-Generated Regression Tests
// Source: calculator.go
// Generated by: AI Regression Testing Framework (Ollama RAG Optimised)
// Framework: go test

package calculator

import "testing"

func TestBasicArithmeticOperations(t *testing.T) {
	// Use positive integer inputs as requested. We use float64 for the functions' types.
	a, b := 5.0, 3.0

	// --- Add Test ---
	expectedAdd := 8.0
	resultAdd := Add(a, b)
	if resultAdd != expectedAdd {
		t.Errorf("Add(%v, %v): Expected %v, got %v", a, b, expectedAdd, resultAdd)
	}

	// --- Subtract Test ---
	expectedSubtract := 2.0
	resultSubtract := Subtract(a + 1.0, b) // Testing (6.0 - 3.0)
	if resultSubtract != expectedSubtract {
		t.Errorf("Subtract: Expected %v, got %v", expectedSubtract, resultSubtract)
	}

	// --- Multiply Test ---
	expectedMultiply := 15.0
	resultMultiply := Multiply(a, b + 2.0) // Testing (5.0 * 5.0) -> Wait, need to adjust inputs for a clean test. Let's use 3 and 5.
	resultMultiply = Multiply(3.0, 5.0)
	if resultMultiply != expectedMultiply {
		t.Errorf("Multiply: Expected %v, got %v", expectedMultiply, resultMultiply)
	}
}

func TestDivideByZero(t *testing.T) {
	// Test case: divisor (b) is zero
	a := 10.0
	b := 0.0

	_, err := Divide(a, b)

	if err == nil {
		t.Fatal("Expected an error when dividing by zero, but got nil")
	}

	expectedErrorMsg := "division by zero is not allowed"
	if err.Error() != expectedErrorMsg {
		t.Errorf("Expected error message '%s', but got '%s'", expectedErrorMsg, err.Error())
	}
}

func TestFactorialNegativeInput(t *testing.T) {
	// Test case: negative input value
	n := -5
	_, err := Factorial(n)

	if err == nil {
		t.Fatal("Expected an error when calculating factorial of a negative number, but got nil")
	}

	expectedErrorMsg := "factorial is not defined for negative numbers"
	if err.Error() != expectedErrorMsg {
		t.Errorf("Expected error message '%s', but got '%s'", expectedErrorMsg, err.Error())
	}
}

func TestClampFunctionality(t *testing.T) {
	type clampTest struct {
		name      string
		value     float64
		min       float64
		max       float64
		wantValue float64
		expectErr bool
	}

	tests := []clampTest{
		// 1. Normal case: value within range
		{"Within Range", 5.0, 0.0, 10.0, 5.0, false},
		// 2. Value below min (should clamp to min)
		{"Below Min Boundary", -3.0, -5.0, 10.0, -5.0, false},
		// 3. Value above max (should clamp to max)
		{"Above Max Boundary", 15.0, 0.0, 10.0, 10.0, false},
		// 4. Invalid range test: min > max (expect error)
		{"Invalid Range Check", 5.0, 10.0, 5.0, 0.0, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := Clamp(tt.value, tt.min, tt.max)

			if tt.expectErr {
				if err == nil {
					t.Fatal("Expected an error because min > max, but got nil")
				}
				// Check for the specific range violation error message
				expectedError := "min must not be greater than max"
				if err.Error() != expectedError {
					t.Errorf("Expected error '%s', got '%s'", expectedError, err.Error())
				}
				return // Test passed if we successfully caught the error
			}

			// For non-error cases
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			// Check result value
			if result != tt.wantValue {
				t.Errorf("Clamp(%v, %v, %v): Expected %v, got %v", tt.value, tt.min, tt.max, tt.wantValue, result)
			}
		})
	}
}
