# AI-Generated Regression Tests
# Source: calculator.py
# Generated by: AI Regression Testing Framework (Ollama RAG Optimised)
# Framework: pytest

import pytest
from calculator import Calculator, percentage, is_prime

# ======================================================================
# Test Group 1: Arithmetic Operations and History Tracking (Requirement 1)
# Test basic arithmetic operations (add, subtract, multiply, power) on the Calculator class while verifying state history updates.
# ======================================================================

def test_arithmetic_operations_and_history():
    """Tests all primary arithmetic functions and verifies state history updates."""
    calc = Calculator()

    # Initial State Check
    assert calc.get_history() == []

    # 1. Test Add (State update)
    result_add = calc.add(2.5, -3.0) # Expect: -0.5
    assert result_add == -0.5
    assert len(calc.get_history()) == 1

    # 2. Test Subtract (State update & float precision check)
    result_subtract = calc.subtract(-10.0, 4.0) # Expect: -14.0
    assert result_subtract == -14.0
    assert len(calc.get_history()) == 2

    # 3. Test Multiply (State update & varied floats)
    result_multiply = calc.multiply(5.5, 2.0) # Expect: 11.0
    assert result_multiply == 11.0
    assert len(calc.get_history()) == 3

    # 4. Test Power (State update & float precision check)
    result_power = calc.power(2.0, 3.0) # Expect: 8.0
    assert result_power == 8.0
    assert len(calc.get_history()) == 4

    # Verify History Content and Length
    history = calc.get_history()
    assert len(history) == 4
    
    # Check specific history entries to ensure correctness of operations recorded
    # Entry 1: add (2.5, -3.0, -0.5)
    assert history[0][0] == "add" and abs(history[0][3] - (-0.5)) < 1e-9
    # Entry 4: power (2.0, 3.0, 8.0)
    assert history[-1][0] == "power" and abs(history[-1][3] - 8.0) < 1e-9


# ======================================================================
# Test Group 2: Division by Zero Exception (Requirement 2)
# Tests division by zero for Calculator.divide, ensuring a ValueError is raised.
# ======================================================================

def test_division_by_zero_raises_valueerror():
    """Ensures that calling divide with b=0 raises a ValueError."""
    calc = Calculator()

    with pytest.raises(ValueError) as excinfo:
        calc.divide(10.0, 0.0)
    
    # Check the specific error message (best practice for exception testing)
    assert "Cannot divide by zero" in str(excinfo.value)


# ======================================================================
# Test Group 3: Percentage Function Boundary & Type Checking (Requirement 3)
# Tests percentage handling total = 0 and non-numeric inputs.
# ======================================================================

@pytest.mark.parametrize("value, total, expected_error", [
    (50.0, 0.0, ValueError),  # Test total = 0
    ('a', 10.0, TypeError),   # Test non-numeric value
    (50.0, None, TypeError),   # Test non-numeric total
    (None, 10.0, TypeError)    # Test non-numeric value (explicitly checking type check logic)
])
def test_percentage_error_handling(value, total, expected_error):
    """Tests percentage function boundary conditions and TypeErrors."""
    with pytest.raises(expected_error):
        percentage(value, total)

# Test a valid case to ensure normal operation is preserved (optional but good practice)
def test_percentage_valid_case():
    assert percentage(25.0, 100.0) == 25.0
    assert percentage(1, 3) == pytest.approx((1/3) * 100)


# ======================================================================
# Test Group 4: Prime Number Edge Cases (Requirement 4)
# Tests is_prime edge cases including negative numbers, '1', floats, and general primes/composites.
# Note: The source code dictates the input type must be int, so we test explicit non-integer inputs causing TypeErrors, and standard integer boundary checks.
# ======================================================================

@pytest.mark.parametrize("input_n, expected", [
    (2, True),          # Smallest prime
    (3, True),
    (17, True),         # Standard prime
    (4, False),         # Smallest composite
    (9, False),         # Composite (3*3)
    (0, False),         # Boundary: less than 2
    (1, False),         # Boundary: not prime
    (-5, False),        # Negative number
])
def test_is_prime_valid_integers(input_n, expected):
    """Tests is_prime function with standard and boundary integers."""
    assert is_prime(input_n) == expected

@pytest.mark.parametrize("bad_input", [
    -1.0,               # Float input (should fail Type Check)
    3.14,               # Float input
    "abc",              # String input
    None                 # NoneType input
])
def test_is_prime_type_checking(bad_input):
    """Tests is_prime function with invalid/non-integer types."""
    with pytest.raises(TypeError):
        is_prime(bad_input)

@pytest.mark.parametrize("value, expected_error", [
    ((2, 3), TypeError), # Non-int input test
])
def test_is_prime_complex_type_checking(value, expected_error):
    """Test is_prime with complex data types."""
    with pytest.raises(expected_error):
        is_prime(value)
