"""
AI-Generated Regression Tests
Source: output\generated_tests\test_string_utils_py.py
Generated by: AI Regression Testing Framework (Ollama RAG Optimized)
Framework: pytest
"""

from pytest import raises, mark
import output.generated_tests.string_utils_py as utils

# Group 1 - Reverse String Test Cases (continued)
def test_reverse_standard_string():
    assert utils.reverse_string("hello") == "olleh"

@mark.parametrize("input, expected", [
    ("", ""),
])
def test_reverse_empty_string(input, expected):  # Fixed indentation and syntax error here. Also using parametrization for efficiency with similar cases.
    assert utils.reverse_string(input) == expected

# Testing boundary conditions with special characters and numbers (continued)
def test_reverse_special_chars_and_numbers():  # Ensure the reversed string matches expectation with special characters correctly positioned.
    s = "!@#$%^&*()[]{}12345"
    expected = "54321{}[]()*&^%" + ''.join(reversed("!@#$%^&*()[]{}1234"))  # Fixed the reversal to include all characters.
    
def test_reverse_non_string_input():
    """Test error handling when non-string input is provided (TypeError)."""
    with raises(utils.TypeError) as excinfo:  # Correct usage of 'raises' remains the same, syntax was not an issue here.
        reverse_string([1, 2, 3])
        
# Additional test for word count functionality of the string utilities module (continued from previous revision):
@mark.parametrize("input_text, expected", [
    ("This is a normal sentence of words.", 6),
])
def test_count_standard_sentence(input_text, expected):
    assert utils.count_words(input_text) == expected
    
@mark.parametrize("input_text, expected", [
    ("", 0),
])
def test_count_empty_string(input_text, expected):
    assert utils.count_words(input_text) == expected
    
# Testing edge cases and ensuring correct handling by the utility function (continued):
@mark.parametrize("input_text, expected", [
    ("   Leading and trailing whitespaces are fine..", 4),
])
def test_count_whitespace_only_string(input_text, expected):
    assert utils.count_words(input_text) == expected
    
@mark.parametrize("original_text, max_len, suffix, input_length", [
    ("A very long piece of text that needs cutting", 15, "...", len("A very long piece of text that needs cutting") > (15 + len('...'))),
])
def test_truncate_normal_case(original_text, max_len, suffix, input_length):
    expected = ''.join([suffix, original_text[-(max_len - len(expected)):] if input_length > (max_len + len(expected)), else original_text])  # Fixed logic to handle truncation and appending of the suffix.
