# AI-Generated Regression Tests
# Source: user_manager.py
# Generated by: AI Regression Testing Framework (Ollama RAG Optimised)
# Framework: pytest

import pytest
from user_manager import (
    UserManager, UserValidationError, UserNotFoundError
)


# =============================================================================
# FIXTURES
# =============================================================================

@pytest.fixture
def manager() -> UserManager:
    """Provides a fresh instance of the UserManager for each test."""
    return UserManager()


# =============================================================================
# TEST CASE 1: ROLE-BASED ACCESS CONTROL BOUNDARIES
# (Admin, Editor, Viewer)
# =============================================================================

def get_user(role: str, id: int = 99) -> 'User':
    """Helper to create a user instance for testing permissions."""
    return User(id=id, username=f"u{id}", email=f"{role}@test.com", role=role)

def test_role_access_control():
    """Tests read/write/delete access boundaries for admin, editor, and viewer roles."""

    # --- Setup Users ---
    admin = get_user("admin")
    editor = get_user("editor")
    viewer = get_user("viewer")

    actions = ["read", "write", "delete_own", "delete_any", "admin"]

    print("\n--- Testing User Roles Permissions ---")

    # 1. Admin Tests: Should pass all actions
    for action in actions:
        assert admin.has_permission(action) is True, f"Admin role failed to grant '{action}' permission."

    # 2. Editor Tests: Read, Write, Delete_own allowed
    for action in ["read", "write", "delete_own"]:
        assert editor.has_permission(action) is True, f"Editor role unexpectedly blocked '{action}'."
    # Check boundaries for Editor
    assert editor.has_permission("delete_any") is False, "Editor should not have delete_any permission."
    assert editor.has_permission("admin") is False, "Editor should not have admin permission."

    # 3. Viewer Tests: Read only
    assert viewer.has_permission("read") is True, "Viewer role incorrectly denied 'read' access."
    for action in ["write", "delete_own", "delete_any", "admin"]:
        assert viewer.has_permission(action) is False, f"Viewer role unexpectedly granted '{action}' permission."


# =============================================================================
# TEST CASE 2: USER VALIDATION (Creation Failures & Duplicates)
# =============================================================================

def test_create_user_validation_failures(manager: UserManager):
    """Tests user creation failure for invalid usernames and emails."""

    # --- Invalid Username Tests (Length/Format) ---
    with pytest.raises(UserValidationError, match="Username must be 3"):
        # Too short
        manager.create_user("a", "valid@email.com")

    with pytest.raises(UserValidationError, match="Username must be 3–50 characters long"):
        # Too long (exceeds standard test length)
        long_username = "A" * 51
        manager.create_user(long_username, "valid@email.com")

    with pytest.raises(UserValidationError, match="Username may only contain letters, digits, and underscores"):
        # Invalid characters (e.g., spaces)
        manager.create_user("bad user name", "valid@email.com")

    # --- Duplicate Username/Email Tests ---
    
    # 1. Successfully create a baseline user
    try:
        user1 = manager.create_user("testuser", "test@example.com", role="editor")
        assert user1 is not None
    except UserValidationError as e:
        pytest.skip(f"Could not setup base user due to {e}")


    # 2. Duplicate Username Failure
    with pytest.raises(UserValidationError, match="Username 'testuser' is already taken"):
        manager.create_user("TESTUSER", "another@email.com") # Case-insensitive check

    # 3. Duplicate Email Failure
    with pytest.raises(UserValidationError, match="Email 'test@example.com' is already registered"):
        manager.create_user("newuser", "test@example.com")


# =============================================================================
# TEST CASE 3: FULL CRUD LIFECYCLE PATH
# (Create -> Read -> Delete)
# =============================================================================

def test_full_crud_lifecycle(manager: UserManager):
    """Tests the full lifecycle path for a user: create, retrieve, delete."""
    
    test_username = "cruduser"
    test_email = f"{test_username}@lifecycle.com"

    # 1. CREATE (Check initial state and successful creation)
    try:
        # Attempt to create the user
        user = manager.create_user(test_username, test_email, role="admin")
        assert user is not None, "User should be successfully created."

    except UserValidationError as e:
        pytest.fail(f"Failed during user creation (CREATE step): {e}")
    except Exception as e:
         # Handle unexpected errors gracefully for test purposes
        pytest.fail(f"Unexpected error during user creation: {type(e).__name__}: {e}")

    # 2. READ (Verify the user can be retrieved)
    try:
        retrieved_user = manager.get_user(test_username)
        assert retrieved_user is not None, "User should exist after creation."
        assert retrieved_user.email == test_email, "Retrieved user email must match original email."

    # 3. DELETE (Ensure clean up happens regardless of previous failures)
    finally:
        try:
            manager.delete_user(test_username)
            print(f"\n--- Successfully deleted and cleaned up {test_username} ---")
        except UserNotFoundError:
             # If the deletion attempt fails because the user doesn't exist, that's fine for cleanup purposes
            pass
