// AI-Generated Regression Tests
// Source: Calculator.java
// Generated by: AI Regression Testing Framework (Ollama RAG Optimised)
// Framework: JUnit 5

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class CalculatorTest {

    private Calculator calculator;

    @BeforeEach
    void setUp() {
        calculator = new Calculator();
    }

    // Test basic arithmetic operations (add, subtract, multiply) with positive and negative inputs
    @Test
    void testBasicArithmeticOperations() {
        // Test Add
        assertEquals(5.0, calculator.add(2.0, 3.0), "Addition of two positives failed");
        assertEquals(-5.0, calculator.add(-2.0, -3.0), "Addition of two negatives failed");
        assertEquals(1.0, calculator.add(3.0, -2.0), "Mixed addition failed");

        // Test Subtract
        assertEquals(1.0, calculator.subtract(3.0, 2.0), "Subtraction (positive result) failed");
        assertEquals(-5.0, calculator.subtract(2.0, 7.0), "Subtraction (negative result) failed");
        assertEquals(5.0, calculator.subtract(-2.0, -7.0), "Subtracting negatives failed");

        // Test Multiply
        assertEquals(6.0, calculator.multiply(2.0, 3.0), "Multiplication of two positives failed");
        assertEquals(6.0, calculator.multiply(-2.0, -3.0), "Multiplication of two negatives failed");
        assertEquals(-6.0, calculator.multiply(2.0, -3.0), "Mixed multiplication failed");
    }

    // Verify division by zero throws ArithmeticException
    @Test
    void testDivisionByZeroThrowsArithmeticException() {
        double dividend = 10.0;
        double divisor = 0.0;

        ArithmeticException exception = assertThrows(ArithmeticException.class, () -> {
            calculator.divide(dividend, divisor);
        });

        assertEquals("Division by zero is not allowed", exception.getMessage());
    }

    // Test factorial for boundary cases (n=0, n=1) and handle negative input error
    @Test
    void testFactorialBoundaryAndNegativeInput() {
        // Boundary Case: n = 0
        assertEquals(1L, calculator.factorial(0), "Factorial of 0 should be 1");

        // Boundary Case: n = 1
        assertEquals(1L, calculator.factorial(1), "Factorial of 1 should be 1");

        // Standard case (optional but good practice)
        assertEquals(24L, calculator.factorial(4), "Factorial of 4 failed");

        // Negative input error handling
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            calculator.factorial(-1);
        });
        assertEquals("Factorial is not defined for negative numbers", exception.getMessage());
    }

    // Test clamp function for value outside min/max bounds and validate structural exception when min > max
    @Test
    void testClampFunction() {
        double min = 10.0;
        double max = 20.0;

        // 1. Value within bounds (should return original value)
        assertEquals(15.0, calculator.clamp(15.0, min, max), "Value inside bounds failed");

        // 2. Value below minimum (should clamp to min)
        double valueBelow = 5.0;
        assertEquals(min, calculator.clamp(valueBelow, min, max), "Clamping below min failed");

        // 3. Value above maximum (should clamp to max)
        double valueAbove = 25.0;
        assertEquals(max, calculator.clamp(valueAbove, min, max), "Clamping above max failed");

        // 4. Structural exception when min > max
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            calculator.clamp(10.0, 30.0, 20.0);
        });
        assertEquals("min must not be greater than max", exception.getMessage());
    }
}
